[options]
list_db = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons,/var/lib/odoo/.local/share/Odoo/addons/19.0,/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$lxJCKKWUUqrVWkvp3VtLaQ$1QdRIBR8A9rZWudJbX3NT3y4klhfk4pmG4JmYM9i4SGgKob5aaVrVqzF7X0unbsRIzftOajFYDMn6ZlSA2wuXg

